---
title: "physo_maps"
author: "Jamie Ash"
date: "2023-02-12"
output: html_document
---

```{r setup, include=FALSE, message = FALSE}
source("functions.R")
source("libraries.R")
source("blooms.R")
library(animation)
library("rerddap")
library("akima")
library("dplyr")
library("ggplot2")
library("mapdata")
library("ncdf4")
library("plot3D")
library(IndexNumR)
library(imputeTS)
library(sp)
#library(rgdal)
library(raster)
library("plotrix") 
rasterOptions(maxmemory = 120e+10, memfrac = 0.9)
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE}
lons = c(-175, -125)
lats = c(17,   40)
e = extent(lons, lats)
sdate = as.Date("2020-07-01")
edate = as.Date("2020-11-25")
```

load sst anom
```{r}
sdate = as.Date("2018-06-15")
edate = as.Date("2018-07-04")

# 'nceiPH53sstd1day'
sstInfo = info('jplMURSST41anom1day',
                url = "https://coastwatch.pfeg.noaa.gov/erddap/")

data = griddap(sstInfo, 
               latitude = e[3:4], 
               longitude = e[1:2], 
               time = c(as.character(sdate),as.character(edate)), 
               fields = 'all')
# "sstAnom"
#for raw sst "sea_surface_temperature"
data = nc_open(data$summary$filename)
ras  = ncvar_get(data, varid = "sstAnom")
lats = ncvar_get(data, varid = "latitude")
lons = ncvar_get(data, varid = "longitude")
time = ncvar_get(data, varid = "time")
time = as.Date(as.POSIXct(time, origin = "1970-01-01"))

nc_close(data)
rm(data)

ras = brick(ras) 
ras = setZ(ras, z = time, name = "time")
extent(ras) = extent(min(lons), max(lons), min(lats), max(lats))
crs(ras) = "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"

ssta = ras
rm(ras)

# ------------------------------------------------------------------------------

sdate = as.Date("2018-07-05")
edate = as.Date("2018-07-30")

# 'nceiPH53sstd1day'
sstInfo = info('jplMURSST41anom1day',
                url = "https://coastwatch.pfeg.noaa.gov/erddap/")

data = griddap(sstInfo, 
               latitude = e[3:4], 
               longitude = e[1:2], 
               time = c(as.character(sdate),as.character(edate)), 
               fields = 'all')
# "sstAnom"
#for raw sst "sea_surface_temperature"
data = nc_open(data$summary$filename)
ras  = ncvar_get(data, varid = "sstAnom")
lats = ncvar_get(data, varid = "latitude")
lons = ncvar_get(data, varid = "longitude")
time = ncvar_get(data, varid = "time")
time = as.Date(as.POSIXct(time, origin = "1970-01-01"))

nc_close(data)
rm(data)

ras = brick(ras) 
ras = setZ(ras, z = time, name = "time")
extent(ras) = extent(min(lons), max(lons), min(lats), max(lats))
crs(ras) = "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"

ssta = stack(ssta, ras)
rm(ras)

# ------------------------------------------------------------------------------
sdate = as.Date("2018-08-01")
edate = as.Date("2018-08-25")

# 'nceiPH53sstd1day'
sstInfo = info('jplMURSST41anom1day',
                url = "https://coastwatch.pfeg.noaa.gov/erddap/")

data = griddap(sstInfo, 
               latitude = e[3:4], 
               longitude = e[1:2], 
               time = c(as.character(sdate),as.character(edate)), 
               fields = 'all')
# "sstAnom"
#for raw sst "sea_surface_temperature"
data = nc_open(data$summary$filename)
ras  = ncvar_get(data, varid = "sstAnom")
lats = ncvar_get(data, varid = "latitude")
lons = ncvar_get(data, varid = "longitude")
time = ncvar_get(data, varid = "time")
time = as.Date(as.POSIXct(time, origin = "1970-01-01"))

nc_close(data)
rm(data)

ras = brick(ras) 
ras = setZ(ras, z = time, name = "time")
extent(ras) = extent(min(lons), max(lons), min(lats), max(lats))
crs(ras) = "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"

ssta = stack(ssta, ras)
rm(ras)

# ------------------------------------------------------------------------------
sdate = as.Date("2018-08-26")
edate = as.Date("2018-09-20")

# 'nceiPH53sstd1day'
sstInfo = info('jplMURSST41anom1day',
                url = "https://coastwatch.pfeg.noaa.gov/erddap/")

data = griddap(sstInfo, 
               latitude = e[3:4], 
               longitude = e[1:2], 
               time = c(as.character(sdate),as.character(edate)), 
               fields = 'all')
# "sstAnom"
#for raw sst "sea_surface_temperature"
data = nc_open(data$summary$filename)
ras  = ncvar_get(data, varid = "sstAnom")
lats = ncvar_get(data, varid = "latitude")
lons = ncvar_get(data, varid = "longitude")
time = ncvar_get(data, varid = "time")
time = as.Date(as.POSIXct(time, origin = "1970-01-01"))

nc_close(data)
rm(data)

ras = brick(ras) 
ras = setZ(ras, z = time, name = "time")
extent(ras) = extent(min(lons), max(lons), min(lats), max(lats))
crs(ras) = "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"

ssta = stack(ssta, ras)
rm(ras)

# ------------------------------------------------------------------------------
sdate = as.Date("2018-09-21")
edate = as.Date("2018-10-15")

# 'nceiPH53sstd1day'
sstInfo = info('jplMURSST41anom1day',
                url = "https://coastwatch.pfeg.noaa.gov/erddap/")

data = griddap(sstInfo, 
               latitude = e[3:4], 
               longitude = e[1:2], 
               time = c(as.character(sdate),as.character(edate)), 
               fields = 'all')
# "sstAnom"
#for raw sst "sea_surface_temperature"
data = nc_open(data$summary$filename)
ras  = ncvar_get(data, varid = "sstAnom")
lats = ncvar_get(data, varid = "latitude")
lons = ncvar_get(data, varid = "longitude")
time = ncvar_get(data, varid = "time")
time = as.Date(as.POSIXct(time, origin = "1970-01-01"))

nc_close(data)
rm(data)

ras = brick(ras) 
ras = setZ(ras, z = time, name = "time")
extent(ras) = extent(min(lons), max(lons), min(lats), max(lats))
crs(ras) = "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"

ssta = stack(ssta, ras)
rm(ras)
gc()

# ------------------------------------------------------------------------------
sdate = as.Date("2020-10-16")
edate = as.Date("2020-11-10")

# 'nceiPH53sstd1day'
sstInfo = info('jplMURSST41anom1day',
                url = "https://coastwatch.pfeg.noaa.gov/erddap/")

data = griddap(sstInfo, 
               latitude = e[3:4], 
               longitude = e[1:2], 
               time = c(as.character(sdate),as.character(edate)), 
               fields = 'all')
# "sstAnom"
#for raw sst "sea_surface_temperature"
data = nc_open(data$summary$filename)
ras  = ncvar_get(data, varid = "sstAnom")
lats = ncvar_get(data, varid = "latitude")
lons = ncvar_get(data, varid = "longitude")
time = ncvar_get(data, varid = "time")
time = as.Date(as.POSIXct(time, origin = "1970-01-01"))

nc_close(data)
rm(data)

ras = brick(ras) 
ras = setZ(ras, z = time, name = "time")
extent(ras) = extent(min(lons), max(lons), min(lats), max(lats))
crs(ras) = "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"

ssta = stack(ssta, ras)
rm(ras)
gc()


# this is so jank
sdate = as.Date("2020-06-15")
edate = as.Date("2020-11-10")
time = seq(from = sdate, to =edate, by= 1)
ssta = setZ(ssta, z = time, name = "time")

ssta = oreant(ssta, flip = "y", t1 = TRUE)
gc()
```

load sst
```{r}
# 'nceiPH53sstd1day'
sstInfo = info('jplMURSST41',
               url = "https://coastwatch.pfeg.noaa.gov/erddap/")

data = griddap(sstInfo, 
               latitude = e[3:4], 
               longitude = e[1:2], 
               time = c(as.character(sdate),as.character(edate)), 
               fields = 'all')
# "sstAnom"
#for raw sst "sea_surface_temperature"
data = nc_open(data$summary$filename)
ras  = ncvar_get(data, varid = "analysed_sst")
lats = ncvar_get(data, varid = "latitude")
lons = ncvar_get(data, varid = "longitude")
time = ncvar_get(data, varid = "time")
time = as.Date(as.POSIXct(time, origin = "1970-01-01"))
ras = brick(ras) 
ras = setZ(ras, z = time, name = "time")
extent(ras) = extent(min(lons), max(lons), min(lats), max(lats))
crs(ras) = "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"

sst = ras

nc_close(data)
rm(data)
rm(ras)
```
load sla
```{r}
# 'nceiPH53sstd1day'
slaInfo = info('nesdisSSH1day',
               url = "https://coastwatch.pfeg.noaa.gov/erddap/")

data = griddap(slaInfo, 
               latitude = e[3:4], 
               longitude = e[1:2], 
               time = c(as.character(sdate),as.character(edate)), 
               fields = 'all')
# "sstAnom"
#for raw sst "sea_surface_temperature"
data = nc_open(data$summary$filename)
ras  = ncvar_get(data, varid = "sla")
lats = ncvar_get(data, varid = "latitude")
lons = ncvar_get(data, varid = "longitude")
time = ncvar_get(data, varid = "time")
time = as.Date(as.POSIXct(time, origin = "1970-01-01"))
ras = brick(ras) 
ras = setZ(ras, z = time, name = "time")
extent(ras) = extent(min(lons), max(lons), min(lats), max(lats))
crs(ras) = "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"

sla = ras

nc_close(data)
rm(data)
rm(ras)
```
loading fsle
```{r, warning = FALSE}
# load fsle from disk
fsle = load_nc(path = "C:\\Users\\james\\Desktop\\jamieslife\\data\\infiles\\case_study\\fsle\\",
               patt = "fsle_po_2018.nc")
extent(fsle) = extent(fsle) - c(360, 360, 0 ,0)

# need yo doa  little self croping
fsle  = oreant(fsle, flip = "y", t1 = TRUE)
fsle = raster::crop(fsle, e)
fsle = timesnip(fsle,  sdate, edate)

gc()
```

Oreanting the maps
```{r}
sla  = oreant(sla, flip = "y", t1 = TRUE)
gc()
sst = oreant(sst, flip = "y", t1 = TRUE)
gc()
```
 
sea surface temperature anomaly
--------------------------------------------------------------------------------
```{r}
# lons = c(-155, -140)
# lats = c(18,   45)
# e = extent(lons, lats)
# temp = crop(ssta, e)
# time = getZ(temp)
```

```{r, eval = FALSE, fig.width = 12, fig.height = 7.5}
wdmap <- getMap(resolution = "high")
colmap = cmocean("balance")(50)
day = ssta[[1]]

image(day,
      ylim = c(17, 40),
      xlim = c(-175, -125),
      xlab = "",
      ylab = "",
      #zlim = c(5, 30),
      col = colmap,
      axes = FALSE)

plot(wdmap,
         xlim = e[1:2],
         ylim = e[3:4],
         asp = 1,
         bg = "black",
         border = "black",
         col = "black",
         #wrap = c(-180, 180),
         add = TRUE)
axis(side = 2, 
     las = 2, 
     lwd = 2, 
     at = c(18, 22, 26, 30, 34, 38),
     mgp = c(1, 0.75, 0), 
     cex.axis = 1.25)
axis(side = 1, 
     las = 1, 
     lwd = 2,
     mgp = c(2, 1, 0),    
     at = c(-170, -160, -150, -140, -130),
     cex.axis = 1.25)
#title(main = list(main), line = line,  adj = adj, cex.main = cex.main)
title(main = "Sea surface temperature anomaly: 2018-06-15", cex.main = 1.75, line = 0.25, adj = 0)

title(ylab = "Latitude", cex.lab = 1.5, line = 2.5)

title(xlab = "Longitude", cex.lab = 1.5, line = 2.5)
box(which = "plot",
        lty = "solid",
        lwd = 3,
        col = colvect("grey12", alpha = 0.9))

#dev.off()
```
 
sea surface temperature 
--------------------------------------------------------------------------------
```{r, eval = FALSE, fig.width = 12, fig.height = 7.5}
wdmap <- getMap(resolution = "high")
colmap = cmocean("thermal")(50)
day = sst[[1]]

image(day,
      ylim = c(17, 40),
      xlim = c(-175, -125),
      xlab = "",
      ylab = "",
      #zlim = c(5, 30),
      col = colmap,
      axes = FALSE)

plot(wdmap,
         xlim = e[1:2],
         ylim = e[3:4],
         asp = 1,
         bg = "black",
         border = "black",
         col = "black",
         #wrap = c(-180, 180),
         add = TRUE)
axis(side = 2, 
     las = 2, 
     lwd = 2, 
     at = c(18, 22, 26, 30, 34, 38),
     mgp = c(1, 0.75, 0), 
     cex.axis = 1.25)
axis(side = 1, 
     las = 1, 
     lwd = 2,
     mgp = c(2, 1, 0),    
     at = c(-170, -160, -150, -140, -130),
     cex.axis = 1.25)
#title(main = list(main), line = line,  adj = adj, cex.main = cex.main)
title(main = "Sea saurface temperature: 2018-06-15", cex.main = 1.75, line = 0.25, adj = 0)

title(ylab = "Latitude", cex.lab = 1.5, line = 2.5)

title(xlab = "Longitude", cex.lab = 1.5, line = 2.5)
box(which = "plot",
        lty = "solid",
        lwd = 3,
        col = colvect("grey12", alpha = 0.9))

#dev.off()
```
sea level anomaly 
--------------------------------------------------------------------------------
```{r, eval = FALSE, fig.width = 12, fig.height = 7.5}
wdmap <- getMap(resolution = "high")
colmap = cmocean("balance")(50)
day = sla[[1]]

image(day,
      ylim = c(17, 40),
      xlim = c(-175, -125),
      xlab = "",
      ylab = "",
      #zlim = c(5, 30),
      col = colmap,
      axes = FALSE)

plot(wdmap,
         xlim = e[1:2],
         ylim = e[3:4],
         asp = 1,
         bg = "black",
         border = "black",
         col = "black",
         #wrap = c(-180, 180),
         add = TRUE)
axis(side = 2, 
     las = 2, 
     lwd = 2, 
     at = c(18, 22, 26, 30, 34, 38),
     mgp = c(1, 0.75, 0), 
     cex.axis = 1.25)
axis(side = 1, 
     las = 1, 
     lwd = 2,
     mgp = c(2, 1, 0),    
     at = c(-170, -160, -150, -140, -130),
     cex.axis = 1.25)
#title(main = list(main), line = line,  adj = adj, cex.main = cex.main)
title(main = "Sea level anomaly: 2018-06-15", cex.main = 1.75, line = 0.25, adj = 0)

title(ylab = "Latitude", cex.lab = 1.5, line = 2.5)

title(xlab = "Longitude", cex.lab = 1.5, line = 2.5)
box(which = "plot",
        lty = "solid",
        lwd = 3,
        col = colvect("grey12", alpha = 0.9))

#dev.off()
```

```{r, fig.width = 12, fig.height = 7.5}
wdmap <- getMap(resolution = "high")

image(fsle, 
      ylim = c(17, 40),
      xlim = c(-175, -125),
      col = gray.colors(10, start = 0, end = 1, gamma = 1),
      axes = FALSE,
      ylab = "",
      xlab = "")
axis(side = 1,
  at = c(-170, -160, -150, -140, -130),
  las = 1, 
  lwd = 2, 
  mgp = c(2, 1, 0), 
  cex.axis = 1.25,
  col = colvect("grey22", alpha = 0.9))
axis(side = 2,
     las  = 2, 
     lwd  = 2, 
     at = c(18, 22, 26, 30, 34, 38),
     mgp  = c(1, 0.75, 0), 
     cex.axis = 1.25,
     col = colvect("grey22", alpha = 0.9))
title(main = "FSLE: 2018-06-15",
      cex.main = 1.75,
      line = 0.25, adj = 0)
title(ylab = "Latitude", cex.lab = 1.5, line = 2.5)
title(xlab = "Longitude", cex.lab = 1.5, line = 2.5)
box(which = "plot",
      lty = "solid",
      lwd = 3,
      col = colvect("grey22", alpha = 0.9))
plot(wdmap, 
   xlim = e[1:2], 
   ylim = e[3:4], 
   asp = 1, 
   bg = "black", 
   border = "black", 
   col = "black", 
   add = TRUE,
   lwd = 2)
```
 
 
 
 
 
 
 